In [ ]:
# Dosya açma
f = open("demofile.txt")


In [ ]:
#Dosya okuma
x = open("demofile.txt", "r", encoding="utf-8" )


In [ ]:
print(x.read())

In [ ]:
# farklı lokasyon için
f = open("D:\\myfiles\welcome.txt", "r")
print(f.read())

In [ ]:
# sadece ilk 5 karakter için
f = open("demofile.txt", "r")
print(f.read(5)) 

In [ ]:
print(f.read(5)) 

In [ ]:
f.close()

In [ ]:
# satır satır okumaya yarar
f = open("demofile.txt", "r")
print(f.readline())
print(f.readline())
f.close()

In [ ]:
# Dosyaya yazı yazdırma
# a ile dosyanın sonuna ekler

In [11]:
f = open("demofile2.txt", "a")
f.write(" bunlar yeni satır")
f.close()

In [19]:
# w ile dosyanın üstüne yazar
f = open("demofile2.txt", "w")
f.write("deneme")

6

In [20]:
f.close()

In [21]:
f = open("demofile2.txt", "w")

f.write("2.cümle")

7

In [26]:
f.close()

In [29]:
f = open("demofile2.txt", "w")


In [33]:
f.write("2.cümle")

7

In [34]:
f.close()

In [4]:
f = open("demofile2.txt", "r+")


In [5]:
print(f.read())

bu bir yazıdır


In [2]:
f.write("bu bir yazıdır")

14

In [3]:
f.close()

In [ ]:
import os
#dosya silme
os.remove("demofile.txt")

In [ ]:
#klasör silme
import os
os.rmdir("newFolder")

In [ ]:
# NUMPY
# numpy Array oluşturma
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

In [ ]:
import numpy as np


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# tupple kullanarak da oluşturulabilir
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

In [ ]:
# 0 boyutlu array
import numpy as np

arr = np.array(42)

print(arr)

In [ ]:
# 1 boyutlu array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

In [7]:
# 2 bouytlu
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
# 3 boyutlu
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
# boyut kontrolü
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
# array indexleme
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
# [1, 2, 3, 4, 5] rakamlarını içeren bir numpy array oluşturunuz

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

In [ ]:
# önce row sonra column bilgisi verilir örnek:

In [21]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('1. satırın 2. elemanı: ', arr[1,3])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1. satırın 2. elemanı:  9


In [ ]:
# 3 boyutlu dizilere ulaşılması

In [24]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 0, 1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2


In [25]:
# Negatif indexleme
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('Last element from 2nd dim: ', arr[-1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10


In [ ]:
# start/end/step

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [ ]:
# Yukarıdaki Numpy arrayde -5. en sona kadar 2 şer 2 şer yazdırınız

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-5::2])

In [30]:
# Numpy array içindeki veri tipi:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [31]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [32]:
# veri tipi belirtebilriiz
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [33]:
# i - i4
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [35]:
# bir string  integer veri olarak tanımlanamaz
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

In [36]:
# Veri tipi değiştirilebilir (int de yazılabilir)
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:

# Bir sonraki kodun çıktısı ne olur

In [37]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
#SLAYT

In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [39]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

In [41]:
#array kendi verisi var mı kontrolü
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
# 2 row 4 adet column var.
#dimenson kontrolü

In [43]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)
print(arr)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [44]:
# 5 boyutlu array oluşturma
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [46]:
# dimenson değiştirme 1-2
import numpy as np

arr = np.array([1, 2, 3, 4, 5,  6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [47]:
#1d to 3d
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [64]:

# Flattening -1boyut
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.reshape(-1))
print(arr)
print(arr.T)
print(arr.reshape(3,2))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]
 [5 6]]


In [65]:
# iterating
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [66]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [69]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print("hey")
    print(x)
            

hey
[[1 2 3]
 [4 5 6]]
hey
[[ 7  8  9]
 [10 11 12]]


In [70]:
# yüksek boyutlu arraylerin yazdırılması için nditter kullanılır
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [136]:
import numpy as np

arr = np.array([[1, 2,99], [3, 4,100],[5, 6,101]])
print(arr)
for x in np.nditer(arr[[0,2], 2]):
  print(x)

[[  1   2  99]
 [  3   4 100]
 [  5   6 101]]
99
101


In [137]:
# Join arrays
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [144]:
#2D
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [142]:
#join stack
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# search

In [145]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

In [ ]:
# sorting
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

In [ ]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

In [ ]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

In [ ]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)